//
// Created by sergoo on 09.10.2023.
//

#ifndef SERVERSIRYOGIANDVITYI_STATICRESPONSE_H
#define SERVERSIRYOGIANDVITYI_STATICRESPONSE_H


class StaticResponse {

};


#endif //SERVERSIRYOGIANDVITYI_STATICRESPONSE_H
